### ISSUE TITLE
Feature Request: Allow ability to exclude certain apps when copying history

### ISSUE THREAD

**Issue by alotia** [PasteBar/PasteBarApp#113]
Please provide an ability to exclude certain apps, such as password managers, when copying to the clipboard history.

**Comment by kurdin** [comment]
@alotia Thank you for your suggestion, but unfortunately, I don't have access to the OS and can't detect which app is used for the user's copy action. This would require a deeper integration into the users' OS (on Mac or Windows), and I don't want to do that. Privacy first.

You have two options with PasteBar. You can mask the password in the clipboard history.

<img width="481" alt="image" src="https://github.com/user-attachments/assets/04917d9f-ab93-4e63-a273-77d4d9160383">
Next time you copy your password, it will be masked.

<img width="353" alt="image" src="https://github.com/user-attachments/assets/99ee465d-f960-4bc0-b385-470c2fd8dfe2">
Or add your password or password prefix to the Stop Words List in the Clipboard History Settings.

<img width="986" alt="image" src="https://github.com/user-attachments/assets/b2a1bd76-344d-4154-b544-d625b320d255">

This should completely ignore adding your password to the clipboard history.
Hope this help.

**Comment by alotia** [comment]
I appreciate the workarounds. Most of the passwords are "random" ones and second suggestion would mean putting the passwords in a "clear text" window, so that won't work, but I will try to use the first suggestion. 

The rest of the app is nicely done, and I feel it will be much better if you are able to provide the deeper integration. I am not sure how that breaks privacy, but I am not a mac/win developer.

Thank you for the quick and detailed reply! Feel free to close this issue as appropriate.

**Comment by kurdin** [comment]
>Most of the passwords are "random" ones and second suggestion would mean putting the passwords in a "clear text" window, so that won't work, but I will try to use the first suggestion.

Yeah, I understand this and I agree it would make a good feature to simply block some apps from detecting the copy action. Thank you again for your suggestions. Maybe other developers can help and suggest solutions on how to create such a detection mechanism, but right now I don't know how. 

Anyone who can help, please feel free to reopen this issue and suggest changes or create a PR!

**Comment by VeRychard** [comment]
There are libraries for GetWindowThreadProcessId and GetForegroundWindow through ref-napi and ffi-napi for Windows.
I don't know much about Macs, but I've found [this link](https://www.macscripter.net/t/determining-path-to-application-without-using-path-to-command/73645/5) which works through AppleScript, might help

**Comment by kurdin** [comment]
Found this: https://hellocode.co/blog/post/tracking-active-process-windows-rust so I'll investigate posibility to track an active app/window when user copies something to the clipboard. 

@VeRychard  Thank you 🙏

**Comment by kurdin** [comment]
Found this another lib: https://github.com/dimusic/active-win-pos-rs?tab=readme-ov-file
and it works on Mac and Windows. Working on apps black list implementation.

**Comment by kurdin** [comment]
Found a way to retrieve and store information about the source of copied item in history and display this on hover. 
<img width="676" alt="Screenshot 2024-07-30 at 19 25 29" src="https://github.com/user-attachments/assets/25db4462-b5f6-4bed-a2ce-4393b00f67cc">

Now working on `Add ignore` an app name from the clipboard history copy action. 

<img width="695" alt="image" src="https://github.com/user-attachments/assets/cc223597-3d54-4e37-851b-8b172c878de9">

**Comment by VeRychard** [comment]
looking good! and such quick 🥳

**Comment by kurdin** [comment]
I added a new option in clipboard history settings to exclude apps from capturing clipboard history. Unfortunately, if an app has a copy to clipboard action from the menubar, it can't be detected; the app window must be in focus or active in the foreground. Anyway, this feature is still useful in many cases.

If anyone wants to try this out, the branch is `exclude-apps-copy-to-history`

<img width="1255" alt="Screenshot 2024-08-02 at 17 56 23" src="https://github.com/user-attachments/assets/53dcf15c-1053-447f-a860-bc0a0f4b818a">

**Comment by VeRychard** [comment]
What do you mean copy to clipboard from the menubar? Is this an iOS thing? I would think when you copy from somewhere it will be active / in foreground.

Anyways nice feature, an additional thing could be to filter by application in the list (now we can filter for video/emoji/etc, but since you would have a list of applications you copied from it could be filtered).

Will check it out 👌

**Comment by kurdin** [comment]
@VeRychard I was talking about this taskbar menu.

![image](https://github.com/user-attachments/assets/c84141c6-91a0-4cd4-bd56-f8da79d49453)

Menu bar is MacOs equivalent of taskbar on Windows. 
![image](https://github.com/user-attachments/assets/129a434d-15d6-42ca-8cfb-1917ba1d853a)

I just tested on Windows and it works fine and won't lose focus to another app on copy. So only copy item from menubar on MacOs would not capture the app name of actual window. Windows users should be good.

**Comment by kurdin** [comment]
I adding an App Filter in clipboard history, this would be useful to quickly find a history items based on copy sources. 

![image](https://github.com/user-attachments/assets/ad8b275d-7102-4bd5-b82c-fae64b4eb671)

**Comment by VeRychard** [comment]
> @VeRychard I was talking about this taskbar menu.
> 
> ![image](https://private-user-images.githubusercontent.com/6027060/354834571-c84141c6-91a0-4cd4-bd56-f8da79d49453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MTI0OTUsIm5iZiI6MTcyMjcxMjE5NSwicGF0aCI6Ii82MDI3MDYwLzM1NDgzNDU3MS1jODQxNDFjNi05MWEwLTRjZDQtYmQ1Ni1mOGRhNzlkNDk0NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTkwOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWI2MmUxNmRlMDM5MTBlNzk2NzBhMzU2NzAxODIyYTgxNTVkM2I3OTc2Y2NlMzVmZThiODRkMjc1MGQ5MDg5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.krSGmPzLrUeXokRIGdDOlrhCebDzLKKEj8wVDT2AHiA)
> 
> Menu bar is MacOs equivalent of taskbar on Windows. ![image](https://private-user-images.githubusercontent.com/6027060/354834978-f2641c60-4809-445c-85b5-70bf8e427f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MTI0OTUsIm5iZiI6MTcyMjcxMjE5NSwicGF0aCI6Ii82MDI3MDYwLzM1NDgzNDk3OC1mMjY0MWM2MC00ODA5LTQ0NWMtODViNS03MGJmOGU0MjdmNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTkwOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU3YzZjNThhMGU5OWNiYjM0ZTgyMDE3N2ZmMGUyYjRkYjQ0Y2E5MjRhNzExNTUyMjIxODJkMjQwYTAwNDdlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.56VLfa753nuNJMIGTFwkqa9B7lqLg9wGEkNIJqjnCg0)
> 
> I just tested on Windows and it works fine and won't lose focus to another app on copy. So only copy item from menubar on MacOs would not capture the app name of actual window. Windows users should be good.

Well I reckon people usually copy from right click context menu and/or Ctrl/Cmd + C (also PasteBar's taskbar icon doesn't have copy to clipboard as I saw), so I don't think that will be an issue :)

**Comment by kurdin** [comment]
Merged #121
