### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by ShlomoCode** [PasteBar/PasteBarApp#115]
Do you have a plan for Android version or is it Mac & PC only?
Thanks!

**Comment by kurdin** [comment]
PasteBar was designed to be a desktop application. It requires a mouse pointer to work correctly, so unfortunately, it would not be possible to recreate the same functionality for an Android or iOS application. In the future, I might create a web version as a client for you to share your saved clips or history, view them, and copy them on mobile devices. But currently, I don't have that in the plan.

Thank you for your question.

**Comment by ShlomoCode** [comment]
Why does a clipboard app need a mouse?
Is this a technical limi, or a result of the current form of construction?

**Comment by kurdin** [comment]
@ShlomoCode This is a good question, but the app was designed that way. It would not work well without a mouse pointer. I use right-click for context menus, drag and drop, and keyboard shortcuts in many places in the app. Additionally, the database and backend logic would need to be changed completely for Android or iOS. You can't just port the current functionality to mobile without changing the core structure, UI/UX, and backend system.
