### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by iQiexie** [PasteBar/PasteBarApp#118]
Will there be a linux version?

**Comment by kurdin** [comment]
@iQiexie I get this question a lot but unfortunately, I could not find a way to recreate some of my core functionality like direct paste from task menu or the app to other apps or shell. It required root access in many Linux distributions like Ubuntu, so I could not find a way to overcome this limitation. 

This library requires root access to simulate key presses: https://github.com/PasteBar/PasteBarApp/tree/main/src-tauri/libs/inputbot

I am not an expect on linux systems, maybe somebody can help and create a PR in the future to point me in the right direction, but right now I have no plans to work on linux version.

**Comment by iQiexie** [comment]
Thank you for the answer!

**Comment by mrdev023** [comment]
@kurdin I think it requires Package Maintainers notes and add udev rules or polkit action / rules. I don't know if the project has all configuration to be built directly on Linux. Maybe I can look a bit
