### ISSUE TITLE
Add an option to remove the app from the Dock on Mac while it's running

### ISSUE THREAD

**Issue by Eric0625** [PasteBar/PasteBarApp#137]
![image](https://github.com/user-attachments/assets/ebe60e95-257e-4867-be5e-f73257f2b6df)

Sorry but I couldn't find an option to turn this off.

**Comment by kurdin** [comment]
@Eric0625  I don't have this option but I'll look into this if that possible to remove the app from the Dock.

**Comment by kurdin** [comment]
Added option in user preferences to hide application icon on Mac

<img width="606" alt="image" src="https://github.com/user-attachments/assets/7e39aa30-fbcc-421e-b5af-f459bff1dc56">

**Comment by kurdin** [comment]
#142 
https://github.com/PasteBar/PasteBarApp/releases/tag/v0.6.0

**Comment by Eric0625** [comment]
Simply amazing, it's working like a charm, thank you!
