### ISSUE TITLE
Enhancement request: a single, unified search field in the Paste Bar window

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [PasteBar/PasteBarApp#148]
What is the reason for having two search fields in the Paste Bar window? Wouldn't it be more intuitive and elegant to have a single search field for all searchable data in the application?
![Screenshot 2024-08-25 at 10 32 12 PM](https://github.com/user-attachments/assets/83090be6-b7eb-4813-8824-64c68b86d287)

**Comment by kurdin** [comment]
I like to have them separately, on the left I use it along with filters to quickly find and filter history items only, on the top I use for everything else. I don't see any problems with that.

**Comment by 0n0mat0p03ia** [comment]
OK, I guess we have a different philosophy about this. I find it more intuitive/simpler to have a single unified search field, but perhaps the benefits of having two will be clearer the more I use the app.
