### ISSUE TITLE
Enhancement request: add descriptive text for  'Auto update on capture' setting

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [PasteBar/PasteBarApp#149]
I have no idea what this setting does.

**Comment by kurdin** [comment]
@0n0mat0p03ia In some cases, you might not want to update the history items list on a new clipboard capture (which would scroll the history to the top). Clipboard history will still be captured and collected by PasteBar, but the list won’t show the updates. Let’s say you want to copy multiple items from 2 days ago. If you copy one item, the list will auto-update and scroll to the top with the copied value, causing you to lose the position of the items you found from 2 days ago. You can temporarily disable the auto-update of the history list on capture and copy as many items as you want from the past.

Hope this helps.

**Comment by 0n0mat0p03ia** [comment]
Ah OK that makes sense, thx.
