### ISSUE TITLE
Enhancement request: support keyboard shortcuts to select items in Quick Paste window

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [PasteBar/PasteBarApp#150]
As a user, I want to quickly select an item in the Quick Paste window. For example, Cmd+1 selects the first item in the list, Cmd+2 selects the second item, etc. This would allow me to select/copy an item in the list without having to take my hands off the keyboard. This feature would be especially useful when the Quick Paste window has been resized to it's largest length, which allows multiple clipboard items to be viewed at once.

**Comment by kurdin** [comment]
@0n0mat0p03ia I have it and you can press CTRL in Quick Paste window and you'll see it. I might need to add Cmd + [number] for better Mac support. I don't remember why but it did not work well so I kept CTRL for Windows and Mac. 

<img width="422" alt="image" src="https://github.com/user-attachments/assets/a8c6703b-3f12-4556-b78f-be62c1bfe2ae">

**Comment by 0n0mat0p03ia** [comment]
Ah, that's great, really happy to see that it's there. As a Mac user I naturally tried Cmd and didn't think of Ctrl (Windows users might naturally try that first). Perhaps this is a discoverability issue, although maybe it's covered in one of the app tours. If not, maybe it could be added.

**Comment by kurdin** [comment]
I'll see if I can add Cmd + [number] on next update.

**Comment by 0n0mat0p03ia** [comment]
Was testing Quick Paste search and Ctrl+NUM, not sure if the following is working as intended:

1. Open Quick Paste
2. Press / to active search
3. Enter a search term that returns a few items
5. Press Ctrl+NUM to select one of the search items

Ctrl+NUM did not work in this scenario. Although numbers were displayed next to each search result, pressing Ctrl+NUM to select one of them generated the default macOS "you can't do that" sound (not sure what it's called). Is this expected?

**Comment by kurdin** [comment]
@0n0mat0p03ia yep, I can confirm that. Thanks for your report and you found the bug.

**Comment by kurdin** [comment]
Released https://github.com/PasteBar/PasteBarApp/releases/tag/v0.6.2
