### ISSUE TITLE
Question: Paste Bar network activity

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [PasteBar/PasteBarApp#153]
The app is making the requests to the following domains:

stats.pastebar.app
updater.pastebar.app

Presumably updater.pastebar.app is checking for app updates, but it would be good to have confirmation. Not sure what data is being sent to stats.pastebar.app?

The app is also making requests to google.com, not sure why? I see it as a saved clip that ships with the app. There are other clips with URLs shipped with the app but AFAIK no calls are being made to them.

**Comment by 0n0mat0p03ia** [comment]
OK, I found github.com in my clipboard history. Could you explain when/why the app makes calls to saved URLs in the history or in saved clips etc.?

**Comment by 0n0mat0p03ia** [comment]
FYI 'Check for App Update' will display 'No Update Available' if the app's network connection to  updater.pastebar.app fails (I'm blocking it at the moment). Not sure if you care or not.

**Comment by kurdin** [comment]
@0n0mat0p03ia Those are good questions.

PasteBar is fully open source, so I don't hide anything, and I don't send or store any of your information. You can look at the source code and find where those calls are made.

1. Call to `updater.pastebar.app` on app start to check if an update is available on GitHub.

https://github.com/PasteBar/PasteBarApp/blob/3601002819b469aa1c3fa7a98fdcd018a4fd4814/packages/pastebar-app-ui/src/App.tsx#L341

https://github.com/PasteBar/PasteBarApp/blob/3601002819b469aa1c3fa7a98fdcd018a4fd4814/src-tauri/tauri.release.conf.json#L49

2. Call to `stats.pastebar.app` I use self-hosted app usage statistics based on the open-source package `https://github.com/plausible/analytics`. All I send is your device id, which you can see in the code below. This is a hashed string created from a combination of your CPU, motherboard, and SSD to identify you as a single user.

https://github.com/PasteBar/PasteBarApp/blob/3601002819b469aa1c3fa7a98fdcd018a4fd4814/packages/pastebar-app-ui/index.html#L13 

https://github.com/PasteBar/PasteBarApp/blob/3601002819b469aa1c3fa7a98fdcd018a4fd4814/packages/pastebar-app-ui/src/layout/NavBar.tsx#L296

I have stats like this, where I can see only device IDs with locations and other technical information. 

<img width="1141" alt="Screenshot 2024-08-25 at 23 30 54" src="https://github.com/user-attachments/assets/93a3b496-7ef0-49b1-b8fd-03fb9f6676b7">

3. When you copy a URL link, PasteBar will create metadata for website card to display it in the history list. You can disable this in the options if you don't need it. I use a free Google service to get the favicon image from the domain you copied to display that icon on the website card.
https://github.com/PasteBar/PasteBarApp/blob/3601002819b469aa1c3fa7a98fdcd018a4fd4814/src-tauri/src/commands/link_metadata_commands.rs#L326

You are always free to clone this repo, remove those lines of code, build your own copy, and use PasteBar without sending anything anywhere.

Hope this helps.

**Comment by 0n0mat0p03ia** [comment]
Thanks for the detailed response, I appreciate it.
