### ISSUE TITLE
Issue: PB opens network connections w/ Auto-Generate and Auto Preview disabled in Settings

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [PasteBar/PasteBarApp#156]
Currently, with the mix of URLs in my clipboard history, PB attempts one network connection after launch (to i.ytimg.com). When the Quick Paste window is opened, PB then attempts additional network connections for the URLs in the clipboard. Is this the expected behavior when `Auto-Generate Link Card Preview` and `Auto Preview Link on Hover` are turned off in Settings?

**Comment by kurdin** [comment]
@0n0mat0p03ia seems like you have a link / url copied in your items for domain `i.ytimg.com`. If `Auto-Generate Link Card Preview` is off, there should be no requests for copied links.

**Comment by 0n0mat0p03ia** [comment]
`Auto-Generate Link Card Preview` is disabled in settings. Based on testing, it appears that links are requested when the Quick Paste window is opened, but not when the main PB window is opened.
![Screenshot 2024-08-28 at 11 14 30 PM](https://github.com/user-attachments/assets/6a17572d-52c6-4526-9e91-4ea7149e3fac)

**Comment by kurdin** [comment]
@0n0mat0p03ia  Thank you for report. I found a bug with settings in Quick Paste window. Fix is coming.

**Comment by kurdin** [comment]
Released https://github.com/PasteBar/PasteBarApp/releases/tag/v0.6.2
