### ISSUE TITLE
cannot preview image

### ISSUE THREAD

**Issue by DearZack** [PasteBar/PasteBarApp#169]
![image](https://github.com/user-attachments/assets/e6e69d8d-5e19-4788-a077-44f2914a2aea)
Hello, this project is very good, but there is a small issue.
When I copy an image, I cannot preview it. Is this the design?

**Comment by kurdin** [comment]
![image](https://github.com/user-attachments/assets/8e9e70c7-6b23-4fdb-a178-a981257c4b50)


@DearZack something is wrong with your system. Image preview should work and when you press Shift + Click on history item with image, you should see a larger preview image in the main panel. 

What is your OS, Windows or Mac ? Can you try to go to any website, right click on any image in your browser and select copy image then look at history, you should see that image in the list.

**Comment by DearZack** [comment]
> What is your OS, Windows or Mac ?

Windows 11

> Can you try to go to any website, right click on any image in your browser and select copy image then look at history, you should see that image in the list.


In this case is ok

When i use `Snipaste 2.9.2` screenshot ，this problem will occur

**Comment by kurdin** [comment]
This seems to be a problem of the app `Snipaste`. You can try to use Snipping Tool to capture screenshots on Windows. 

https://support.microsoft.com/en-us/windows/use-snipping-tool-to-capture-screenshots-00246869-1843-655f-f220-97299b865f6b#ID0EDD=Windows_11

**Comment by happybaby8882** [comment]
> > What is your OS, Windows or Mac ?
> 
> Windows 11
> 
> > Can you try to go to any website, right click on any image in your browser and select copy image then look at history, you should see that image in the list.
> 
> In this case is ok
> 
> When i use `Snipaste 2.9.2` screenshot ，this problem will occur

Has this issue been resolved? I've got the same problem, and I use the `Snipaste` too.

**Comment by He1224507974** [comment]
同问

**Comment by ZeyuDong1** [comment]
> This seems to be a problem of the app `Snipaste`. You can try to use Snipping Tool to capture screenshots on Windows.
> 
> https://support.microsoft.com/en-us/windows/use-snipping-tool-to-capture-screenshots-00246869-1843-655f-f220-97299b865f6b#ID0EDD=Windows_11

Hi my previous clipboard app can preview image copy from snipaste. I switch to this app because I really like it;s functios. I really hope this app can support snipaste.
