### ISSUE TITLE
Feature Request: Ditto's "Friends"

### ISSUE THREAD

**Issue by DearZack** [PasteBar/PasteBarApp#179]
Is it possible to achieve functions similar to Ditto's "Friends"? There are two devices in the local area network that require sharing clipboard 
[Ditto](https://github.com/sabrogden/Ditto)

**Comment by kurdin** [comment]
> Is it possible to achieve functions similar to Ditto's "Friends"? There are two devices in the local area network that require sharing clipboard [Ditto](https://github.com/sabrogden/Ditto)

No, it's not possible right now with PasteBar.
