### ISSUE TITLE
Clipboard history failed to record the latest clipboard content in most cases 

### ISSUE THREAD

**Issue by shiquda** [PasteBar/PasteBarApp#185]
![PixPin_2024-11-17_12-12-58](https://github.com/user-attachments/assets/1f04e838-6908-4daf-ad34-ebc90ce57dab)

The software failed to record the content when I directly use `Ctrl + C` to copy something on the webpage. However it worked when I copy something on the address bar. It worked well when copying images.

Environment: Windows 11 23H2, PasteBar version 0.6.2.

**Comment by kurdin** [comment]
@shiquda Thank you for reporting, this is strange issue you having, please make sure your browser is not in exclude list in Clipboard History Settings. 

<img width="915" alt="image" src="https://github.com/user-attachments/assets/4a000f75-81cb-4921-87f1-3511e2f5575a">

If not, try to copy different selected text using right click > Copy from context menu instead of using `Ctrl + C`

**Comment by kurdin** [comment]
@shiquda sorry to hear you having this problem. Maybe you can try to remove and reinstall the App ? I don't have any other users reports with such a problem on Windows 11. I am on a Mac myself but I will try to get my hands on Windows 11 to see if I can reproduce this error. I'll let you know.

**Comment by shiquda** [comment]
It seems I found something wired: in the cases that clipboard history failed to record, when I hode `Ctrl + C` a little longer, it can then successfully record it.

![PixPin_2024-11-17_14-59-03](https://github.com/user-attachments/assets/c318e847-71da-4fc4-b606-c72ccd63adbc)

**Comment by shiquda** [comment]
> It seems I found something wired: in the cases that clipboard history failed to record, when I hode `Ctrl + C` a little longer, it can then successfully record it.
> 
> ![PixPin_2024-11-17_14-59-03](https://private-user-images.githubusercontent.com/104683621/386927286-c318e847-71da-4fc4-b606-c72ccd63adbc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjcwNzUsIm5iZiI6MTczMTgyNjc3NSwicGF0aCI6Ii8xMDQ2ODM2MjEvMzg2OTI3Mjg2LWMzMThlODQ3LTcxZGEtNGZjNC1iNjA2LWM3MmNjZDYzYWRiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNjU5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZiNDU1MjAzMzhiZjliZDI4ZjcxMmRkMWFhYjc4NWZiMGVmYjRjMjMwYjczOWE2ZTQ1ZDY4YjYxYzkxNmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ovL8fzF9bPrHqK_boL4_CcucKbST8QnSEnMFffLYvEU) [ ![PixPin_2024-11-17_14-59-03](https://private-user-images.githubusercontent.com/104683621/386927286-c318e847-71da-4fc4-b606-c72ccd63adbc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjcwNzUsIm5iZiI6MTczMTgyNjc3NSwicGF0aCI6Ii8xMDQ2ODM2MjEvMzg2OTI3Mjg2LWMzMThlODQ3LTcxZGEtNGZjNC1iNjA2LWM3MmNjZDYzYWRiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNjU5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZiNDU1MjAzMzhiZjliZDI4ZjcxMmRkMWFhYjc4NWZiMGVmYjRjMjMwYjczOWE2ZTQ1ZDY4YjYxYzkxNmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ovL8fzF9bPrHqK_boL4_CcucKbST8QnSEnMFffLYvEU) ](https://private-user-images.githubusercontent.com/104683621/386927286-c318e847-71da-4fc4-b606-c72ccd63adbc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjcwNzUsIm5iZiI6MTczMTgyNjc3NSwicGF0aCI6Ii8xMDQ2ODM2MjEvMzg2OTI3Mjg2LWMzMThlODQ3LTcxZGEtNGZjNC1iNjA2LWM3MmNjZDYzYWRiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNjU5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZiNDU1MjAzMzhiZjliZDI4ZjcxMmRkMWFhYjc4NWZiMGVmYjRjMjMwYjczOWE2ZTQ1ZDY4YjYxYzkxNmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ovL8fzF9bPrHqK_boL4_CcucKbST8QnSEnMFffLYvEU) [ ](https://private-user-images.githubusercontent.com/104683621/386927286-c318e847-71da-4fc4-b606-c72ccd63adbc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjcwNzUsIm5iZiI6MTczMTgyNjc3NSwicGF0aCI6Ii8xMDQ2ODM2MjEvMzg2OTI3Mjg2LWMzMThlODQ3LTcxZGEtNGZjNC1iNjA2LWM3MmNjZDYzYWRiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNjU5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZiNDU1MjAzMzhiZjliZDI4ZjcxMmRkMWFhYjc4NWZiMGVmYjRjMjMwYjczOWE2ZTQ1ZDY4YjYxYzkxNmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ovL8fzF9bPrHqK_boL4_CcucKbST8QnSEnMFffLYvEU)

And these content can be recorded by the built-in windows clipboard recorder.
And in somewhere (like the URL bar), the clipboard history can instantly record the content.

**Comment by shiquda** [comment]
Thanks! I'll reinstall this app and see if this problem remains.

**Comment by kurdin** [comment]
If you copy a small text with `Ctrl + C` and you see it's not recorded by PasteBar, but if you paste it regularly with `Ctrl + V` does it work ? Can you please try to add a new user account to your Windows system without any other program running in the background and install PasteBar only, see if this will work? It could be some other program on your system interfering with the PasteBar app.

**Comment by shiquda** [comment]
> If you copy a small text with `Ctrl + C` and you see it's not recorded by PasteBar, but if you paste it regularly with `Ctrl + V` does it work ? Can you please try to add a new user account to your Windows system without any other program running in the background and install PasteBar only, see if this will work? It could be some other program on your system interfering with the PasteBar app.

Yes, after closing some other apps, it worked. I'll figure out which program exactly interfered PasteBar. Sorry for the inconvenience.

**Comment by kurdin** [comment]
> Yes, after closing some other apps, it worked. I'll figure out which program exactly interfered PasteBar. Sorry for the inconvenience.

Glad it worked!

**Comment by shiquda** [comment]
It is [GameViewer](https://gv.163.com/) that interferes PasteBar, which is a Chinese software, similar to Parsec.

**Comment by kurdin** [comment]
> It is [GameViewer](https://gv.163.com/) that interferes PasteBar, which is a Chinese software, similar to Parsec.

Thanks for letting me know. Others might be having the same problem, so it’s helpful to know that exact program interfering with PasteBar.
